[package]
name = "yew-video-streaming"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
yew = "0.19"
wasm-bindgen = "0.2"
wasm-bindgen-futures = "0.4"
wasm-logger = "0.2"
js-sys = "0.3"

[dependencies.web-sys]
version = "0.3"
features = [
	"Navigator", "MediaDevices", "console", "Document", "MediaStreamConstraints"
]

